apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-order
  template:
    metadata:
      labels:
        app: service-order
    spec:
      containers:
      - name: service-order
        image: dat35/service_order:latest # Thay đổi tên thành tên Docker Hub của bạn
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service-order
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: service-order
