apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-payment
  template:
    metadata:
      labels:
        app: service-payment
    spec:
      containers:
      - name: service-payment
        image: dat35/service_payment:latest # Thay đổi tên thành tên Docker Hub của bạn
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: service-payment
spec:
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
  selector:
    app: service-payment
